### PR TITLE
nall: fix string.format() bug reaching 1 byte beyond allocated array bounds

### PR DESCRIPTION
**Pull request by JamesDunne**

### CODE REVIEW

**Comment by Alcaro** [comment]
I can reproduce a Valgrind warning in string::format using
```
#include <nall/string.hpp>
int main() { puts(nall::string("{0}").format("5")); }
```
but your proposed patch does not fix it.

From what I can see, the correct fix would be `memory::move(&data[x], &data[x + difference], remaining - difference);`.

**Comment by JamesDunne** [comment]
Ah that might be better. I didn't do any comprehensive testing myself.

**Comment by JamesDunne** [comment]
Trying to replicate the valgrind issue on my mac but valgrind is having compatibility issues with anything newer than High Sierra. On Mojave here.

**Comment by JamesDunne** [comment]
Finally was able to reproduce the valgrind issue on linux and patched appropriately.

**Comment by Screwtapello** [comment]
Thank you very much @JamesDunne for spottiing that error, and thank you also to @Alcaro for reviewing it more quickly and thoroughly than I could!

**Pull request merged**
